### ISSUE TITLE
How to mute/unmute across different apps in Windows?

### ISSUE THREAD

**Issue by shonilchi** [SaifAqqad/AHK_MicMute#1]
Your script works... Thanks. I am using MS Teams and Skype in my system and I need one AHK hotkey to mute/unmute on both of these. How do I achieve this from your script? Could you please help?

**Comment by SaifAqqad** [comment]
The script actually mutes your microphone from the OS so it should be muted for both Teams and Skype.
the mute button in Teams is not affected by this, so even if it shows the microphone as unmuted, it's probably muted.
you can make sure that it's muted in Windows settings -> System -> Sound
