### ISSUE TITLE
Mute button stuck on modifiers like scroll-lock

### ISSUE THREAD

**Issue by dyppz** [SaifAqqad/AHK_MicMute#102]
Occasionally, the mute/unmute toggle will act as if it's held down when using a key like scroll-lock. Is it possible to implement some sort of soft cooldown to prevent this from happening?

**Comment by SaifAqqad** [comment]
I'm not sure I completely understand the issue

is the toggle hotkey set to scroll-lock or does the toggle hotkey get stuck when clicking scroll-lock at the same time?

**Comment by dyppz** [comment]
Sorry if I've been unclear.

I have set my toggle to Scroll-Lock, it's a key I use the least and was a good choice on my limited keyboard.

Occasionally, when pressing scroll-lock, expecting the toggle, it will get stuck as if the key was held down causing a rapid mute/unmute cycle.

I suggested a cooldown for the toggle when the key is pressed as a possible means of preventing the toggle from getting stuck as if it were held down.

I have also tested this with multiple keyboards and can confirm that it is not the key on my keyboard itself getting stuck.

**Comment by SaifAqqad** [comment]
I had no luck reproducing this issue, perhaps it might be caused by another program with a conflicting shortcut? or if your keyboard has a driver utility (like razer or logitech)

Could you post your config.json file as well? you can access it by holding the <kbd>shift</kbd> key while clicking _Edit Configuration_ from the tray menu

**Comment by dyppz** [comment]
I figured it out, it was a key-binding inside of Xbox Accessories of all things, where my controller had Scroll Lock also bound.

Sorry to have taken your time, thank you.
