### ISSUE TITLE
[Request] Mute on startup

### ISSUE THREAD

**Issue by herrenP** [SaifAqqad/AHK_MicMute#13]
Could you consider adding an option to always mute the mic on startup?

**Comment by SaifAqqad** [comment]
OK, I'll look into it today

**Comment by SaifAqqad** [comment]
Hey, I just pushed the commit.
you can try it by [downloading the new executable](https://github.com/SaifAqqad/AHK_MicMute/releases/download/latest_commit/MicMute.exe) and replacing the old one.
I didn't add it to the UI though, for now you can open the config file in any text editor by holding shift when clicking `Edit configuration` and set `"MuteOnStartup"` to `1`.

**Comment by herrenP** [comment]
Thanks! I'll try it when I'm back at home tonight. 🙂

**Comment by herrenP** [comment]
Yeah, seems to work just fine. When I start the app:
- the icon is shown as muted
- mic is muted when I check in Discord
- the mute sound is played
- and I can toggle between mute and unmute just like before
