### ISSUE TITLE
Woke PC up from sleep to see this. Not sure what this means?

### ISSUE THREAD

**Issue by apotenza92** [SaifAqqad/AHK_MicMute#24]
This window appeared after waking up my PC from sleep:
![image](https://user-images.githubusercontent.com/53612685/120909939-dd5e5e80-c6bd-11eb-990d-24dc6510fa1c.png)

After clicking Yes, the configuration window opened with broken graphics:
![image](https://user-images.githubusercontent.com/53612685/120909962-0383fe80-c6be-11eb-8840-186a7acc002b.png)

Unsure what the error means, but thought I would post here.

Thanks

**Comment by SaifAqqad** [comment]
Hey, thanks for reporting this

I have looked into this and I tried to reproduce it but I couldn't.

did it happen only once? and was your configuration affected or not?

**Comment by apotenza92** [comment]
Has only happened to me once. Once I quit and restart the program everything was back to normal and my configuration hadn't changed. Weird. I'll post here if it happens again.
