### ISSUE TITLE
Option to show overlay only when mic muted

### ISSUE THREAD

**Issue by shemanaev** [SaifAqqad/AHK_MicMute#26]
Games interfaces often pretty cluttered already and displaying icon only when it's meaningful (for me) would be great. Thank you.

**Comment by SaifAqqad** [comment]
I've added this option in [1.1.0](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/1.1.0), just update to the new version and try it out

**Comment by shemanaev** [comment]
Works great, thank you!
