### ISSUE TITLE
Windows defender finds Trojan

### ISSUE THREAD

**Issue by toolewdpersona** [SaifAqqad/AHK_MicMute#29]
I'm not special in this, but in the new version 1.1.1 Windows defender finds Trojan.
I think not every user decides to install such a version.

version 1.1.1
https://www.virustotal.com/gui/file/d08f270e9baf21a9465a352a9895305f960342c76864044d43fd08d8de0d14cb/detection

version 1.1.0
https://www.virustotal.com/gui/file/ba2c8a5bfd1b737901772cbd3d354885dd08aa9608ab81644429f9eca4396c3d/detection

it's okay?

**Comment by SaifAqqad** [comment]
Yeah there's nothing wrong with the build.

I will submit it to Microsoft now, though it takes at least a day to remove the detection 😞

**Comment by SaifAqqad** [comment]
They removed the detection 🎉 
![image](https://user-images.githubusercontent.com/47293197/128902084-5c14f6f9-e91e-4517-8dde-ca1c3979e7a0.png)
https://www.virustotal.com/gui/file/d08f270e9baf21a9465a352a9895305f960342c76864044d43fd08d8de0d14cb/detection
