### ISSUE TITLE
[Request] Set Output Device for PTT Sound Feedback

### ISSUE THREAD

**Issue by Uronic** [SaifAqqad/AHK_MicMute#30]
Currently, there is no way to set another output device for MicMute. I tried it through the windows settings as well and it does not really change it either.

**Comment by SaifAqqad** [comment]
Hey, I've looked into this and it looks like there's no easy way to implement it, I would need to use Windows's [WASAPI](https://docs.microsoft.com/en-us/windows/win32/coreaudio/wasapi) which I'm not familiar with at all (right now MicMute just uses a simple call to [PlaySound](https://docs.microsoft.com/en-us/previous-versions/dd743680(v=vs.85)))

**Comment by Uronic** [comment]
> Hey, I've looked into this and it looks like there's no easy way to implement it, I would need to use Windows's [WASAPI](https://docs.microsoft.com/en-us/windows/win32/coreaudio/wasapi) which I'm not familiar with at all (right now MicMute just uses a simple call to [PlaySound](https://docs.microsoft.com/en-us/previous-versions/dd743680(v=vs.85)))

I am not really too familiar or experienced with AHK and all of this but I desperately went to google in an attempt to help and found something about BASS Library. I am probably not helping but I thought it was worth a try.

**Comment by SaifAqqad** [comment]
I've looked into this bass library and it looks surprisingly good and easy to use. I'll see what I can do :D

**Comment by Uronic** [comment]
A volume slider for the sound feedback would be a nice touch in my opinion.

**Comment by SaifAqqad** [comment]
You can use the windows volume mixer for that, it works with both the dev build and older versions

**Comment by Uronic** [comment]
Done in Development Build.
