### ISSUE TITLE
[Request] Support for disconnected devices

### ISSUE THREAD

**Issue by Uronic** [SaifAqqad/AHK_MicMute#32]
I am on a laptop and use different microphones depending on where I am. I was wondering if it was possible for MicMute to list devices as [DISCONNECTED] for example and ignore them on startup instead of stopping MicMute from opening and showing an invalid configuration message.

**Comment by SaifAqqad** [comment]
I could make it so the configured microphone(s) will be listed in the UI even if they're unavailable but it would just revert to the default microphone when actually muting/unmuting

**Comment by Uronic** [comment]
> I could make it so the configured microphone(s) will be listed in the UI even if they're unavailable but it would just revert to the default microphone when actually muting/unmuting

That would be bad for my case since I use Voicemeeter and that would cause my Voicemeeter Output recording device to get muted. Maybe just make it so that they're listed in the UI but it doesn't revert to anything and just mutes what is selected. My internal laptop mic is what I use when I am not at my setup so its always connected and selected on MicMute.

**Comment by SaifAqqad** [comment]
So it should just fail silently?

**Comment by Uronic** [comment]
> So it should just fail silently?

If what that means is it tries to mute all selected devices but the ones that it is not able to due to them not being found or connected it just ignores through failing to mute then yes that is good in my opinion.

**Comment by SaifAqqad** [comment]
I have implemented the following:
 1- if a configured microphone is unavailable, muting/unmuting it will fail without giving any feedback
 2- if only one microphone is configured and it's unavailable, the tray icon will become the default micmute icon and the tray tooltip will be 'Microphone Unavailable'
 3- The UI will always include the microphones that are in the config file regardless of availability
  
You can test it in the [latest dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit) if you want.

**Comment by Uronic** [comment]
Just tested it out, it works. Thanks.

Done in Development Build
