### ISSUE TITLE
[Request] Frequently check if Mic is still muted in Windows

### ISSUE THREAD

**Issue by Uronic** [SaifAqqad/AHK_MicMute#33]
Some programs like to mess with recording devices for some reason. (For me it is Black Ops 2) If it only unmuted the default recording device it would make more sense. I don't have both my mics selected as default or default communication devices and it still tries to unmute everything. For BO2, it unmutes when the game first starts up and then whenever you mess with the voice chat settings it also unmutes again. 

I think that if MicMute checked whether the mics selected in the UI were actually still muted within windows when they're supposed to it will help with this issue.

**Comment by SaifAqqad** [comment]
Right now MicMute updates the microphones state every [1.5 seconds](https://github.com/SaifAqqad/AHK_MicMute/blob/ad7cf4539b4b7c4f8ddadb8528dc472701103e6d/src/MicMute.ahk#L215), so there shouldn't be a problem using it with these programs.

though I might change it so it can listen to changes made to the microphones in the OS and update the state immediately.
but other than that I don't think MicMute should prevent other apps from unmuting the microphones, that might lead to a lot of problems.

**Comment by Uronic** [comment]
> Right now MicMute updates the microphones state every [1.5 seconds](https://github.com/SaifAqqad/AHK_MicMute/blob/ad7cf4539b4b7c4f8ddadb8528dc472701103e6d/src/MicMute.ahk#L215), so there shouldn't be a problem using it with these programs.
> 
> though I might change it so it can listen to changes made to the microphones in the OS and update the state immediately.
> but other than that I don't think MicMute should prevent other apps from unmuting the microphones, that might lead to a lot of problems.

Updates the microphone state as in what? I am re-testing to make sure right and both mics selected stay unmuted even after 1.5 seconds with no feedback to tell me, are you referring to the tray icon changing? For problems relating to MicMute not allowing other programs to unmuting microphones, I think that defeats the purpose of having push to talk, or toggling mic or anything related to the user themselves wanting to keep their microphones muted.

**Comment by SaifAqqad** [comment]
> Updates the microphone state as in what? I am re-testing to make sure right and both mics selected stay unmuted even after 1.5 seconds with no feedback to tell me

Updates the state as in the tray icon, overlay icon, tooltips, etc. It will update those based on the current state of the mic (muted/unmuted), however, it will not keep the microphone muted just because it was muted before and another app unmuted it

> For problems relating to MicMute not allowing other programs to unmuting microphones, I think that defeats the purpose of having push to talk, or toggling mic or anything related to the user themselves wanting to keep their microphones muted.

Most apps don't have that problem, and forcing the mic state can break functionality in some apps or result in the user having to unmute the mic from both that app and MicMute (in this case, the app is also forcing the unmute but not checking if it's actually unmuted), but still, I could make an optional feature to always force the mic's state.

**Comment by Uronic** [comment]
> > Updates the microphone state as in what? I am re-testing to make sure right and both mics selected stay unmuted even after 1.5 seconds with no feedback to tell me
> 
> Updates the state as in the tray icon, overlay icon, tooltips, etc. It will update those based on the current state of the mic (muted/unmuted), however, it will not keep the microphone muted just because it was muted before and another app unmuted it
> 
> > For problems relating to MicMute not allowing other programs to unmuting microphones, I think that defeats the purpose of having push to talk, or toggling mic or anything related to the user themselves wanting to keep their microphones muted.
> 
> Most apps don't have that problem, and forcing the mic state can break functionality in some apps or result in the user having to unmute the mic from both that app and MicMute (in this case, the app is also forcing the unmute but not checking if it's actually unmuted), but still, I could make an optional feature to always force the mic's state.

Oh. Sorry, I was not aware. Yeah an optional setting for this sounds nice since trying to fix this will just cause more problems for other people. Just want to ask can you also make it so the sound feedback also changes state with the tray icon and tooltips?

**Comment by SaifAqqad** [comment]
> Just want to ask can you also make it so the sound feedback also changes state with the tray icon and tooltips?

Do you mean it should also give feedback when the state changes?

**Comment by Uronic** [comment]
> > Just want to ask can you also make it so the sound feedback also changes state with the tray icon and tooltips?
> 
> Do you mean it should also give feedback when the state changes?

Yes like when the microphone gets unmuted through windows and the tray icon and tooltip changes, the sound feedback also makes the ptt_off sound for example.

**Comment by SaifAqqad** [comment]
No the sound and onscreen feedback are only called when the state is changed by MicMute (hotkeys or tray toggle), and I think they should stay that way, otherwise it would be annoying for most people

**Comment by Uronic** [comment]
> No the sound and onscreen feedback are only called when the state is changed by MicMute (hotkeys or tray toggle), and I think they should stay that way, otherwise it would be annoying for most people

Oh ok I get that.

**Comment by SaifAqqad** [comment]
I have added the option to force the mic state, this will prevent other apps from muting/unmuting your microphones.

You can test it out in the [dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit) if you want
