### ISSUE TITLE
[Request] Sound that loops while push to talk or toggle talk is on.

### ISSUE THREAD

**Issue by Uronic** [SaifAqqad/AHK_MicMute#34]
Currently, there are options in MicMute to add custom sounds for muting and unmuting the microphone.

I think adding an option for a custom sound that loops for the duration that the microphone is unmuted would be a fun feature.

Not really necessary and important, just a fun feature I thought of.

**Comment by SaifAqqad** [comment]
I'm sorry but I won't do this.
