### ISSUE TITLE
Hotkey to toggle monitoring

### ISSUE THREAD

**Issue by tonn** [SaifAqqad/AHK_MicMute#37]
There is option in windows mic settings - "Listen to this device". It would be awesome if we can quickly toggle it by hotkey - to be sure that our sound is clear and loud enough at any time of conversation.

**Comment by SaifAqqad** [comment]
There's no way to do this with the windows API. [see MSDN](https://social.msdn.microsoft.com/Forums/Windows/en-US/f243f5e2-c2ac-4cec-8f57-0825cab48af5/access-to-the-quotlisten-to-this-devicequot-setting?forum=windowspro-audiodevelopment)

**Comment by tonn** [comment]
I found ahk solution for this. It emulates user input and looks tricky. But it's better then nothing...
https://gist.github.com/tonn/f3970df5f5051b778c1e92b48179f968
