### ISSUE TITLE
Mic is unmuted even though "Mute on startup" is enabled

### ISSUE THREAD

**Issue by herrenP** [SaifAqqad/AHK_MicMute#39]
I updated MicMute yesterday (not sure which version I came from - but it was most likely months old) to 1.2.2 and now the mic is enabled after a reboot even though I have enabled "Mute on startup". At first I thought this might be because in the new version the app now start on startup using Task Scheduler, but I have tested by going back to having a shortcut in `shell:startup` without seeing any difference. I have also disabled and re-enabled "Mute on startup" to see if there was some kind of syncronization issue with the settings. This did not help either.

**Comment by herrenP** [comment]
I just now removed `config.json` but the issue remain.

**Comment by SaifAqqad** [comment]
Can you post the contents of your `config.json` file?

Also could you post a screenshot of the logs window?
To open it, just right click the MicMute icon in the taskbar and then while holding <kbd>Shift</kbd> on your keyboard, click on `Help`.

**Comment by SaifAqqad** [comment]
Commit 0fdc2a3 should fix this.
If you want, you can test the [development build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit), or as a workaround, you can temporarily select your microphone in the config window instead of the `default` option
