### ISSUE TITLE
FeatureRequest: Mute All or several with single hotkey

### ISSUE THREAD

**Issue by toxic0berliner** [SaifAqqad/AHK_MicMute#51]
Hello,
It seems that if I setup the same hotkey to toggle multiple microphones it refuses to work claiming conflicting hotkeys.
I think it makes sense to be able to mute several microphones with the same hotkey, possibly even have a "virtual microphone" named "all inputs" that would automatically apply the action mute/unmute to all microphones and for which I setup a single hotkey and I do it only once instead of going into each microphone to record the same hotkey each time.

**Comment by SaifAqqad** [comment]
This is a good idea, I will look into it.

**Comment by SaifAqqad** [comment]
I've added this feature in the latest release ([v1.2.4](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/1.2.4))

**Comment by toxic0berliner** [comment]
works like a charm, thanks a lot @SaifAqqad !
