### ISSUE TITLE
Hotkey stops working in GTA 5

### ISSUE THREAD

**Issue by Uronic** [SaifAqqad/AHK_MicMute#52]
I don't know if the issue exists in other games too but when I launch GTA 5 (not administrator), my MicMute push to talk hotkey stops working. MicMute is running as administrator.

**Comment by SaifAqqad** [comment]
Does the hotkey work when you minimize GTA ?

**Comment by Uronic** [comment]
> Does the hotkey work when you minimize GTA ?

No but...

I was looking through the settings after I made this issue. It seems that when I enable the voice chat setting (which is turned off by default) and make sure my microphone is selected and on in-game, it works.

Weird, but I guess anyone who has this issue in the future knows this fix now.

**Comment by SaifAqqad** [comment]
That is weird

I'm gonna test this out now

**Comment by SaifAqqad** [comment]
It seems that GTA actually runs as admin by default.
I've tested it with both MicMute and GTA running as admin + voice chat is off, and it seems to be working just fine 🤔

https://user-images.githubusercontent.com/47293197/148448719-59180cd2-1db1-4440-a77b-b339040a2619.mp4

**Comment by Uronic** [comment]
Oh. I don't know what caused my issue to happen then. I just know that the moment I turned on voice chat it started working again. I will close this issue I guess if it works for you.
