### ISSUE TITLE
Crashed when trying to edit config

### ISSUE THREAD

**Issue by xuiey** [SaifAqqad/AHK_MicMute#53]
I run it, when I try to right click and edit it from hotbar it lags and loads then disappears.

**Comment by xuiey** [comment]
Invalid memory read/write
Line#
1799L this.devices[A_Index]:= StrGet(NumGet(devInfo, 0, "UInt"),"UTF-8")
Program unstable and will exit.

**Comment by SaifAqqad** [comment]
Does this happen frequently?
