### ISSUE TITLE
[Feature Request] Voicemeeter Integration

### ISSUE THREAD

**Issue by Uronic** [SaifAqqad/AHK_MicMute#54]
Basically a feature that allows to pick a Voicemeeter Hardware Input 1,2,3,4,5 B1,2,3 bus for push to talk. I could do this with Voicemeeter's included MACRO Buttons but the hotkeys on there have many issues such as not working in some fullscreen games.

**Comment by roughnecks** [comment]
Leaving my comment here because it seems useless to open another issue.

When in "Sound Feedback" Output Device I select a VB-Cable (VoiceMeeter) or any other channel which is not "Default", it looks like sound notifications don't play nicely.. Moreover the visualization spectrum also has issues appearing.

@Uronic can you confirm?

Thanks

**Comment by roughnecks** [comment]
> I have stopped using AHK MicMute for a while since I am playing games which possibly falsely ban you for using Autohotkey (The backend of MicMute).
> 
> I do not remember having this issue when I did use it though.
> 
> I use Voicemeeter's MacroButtons in administrator mode for push to talk now if you're wondering.

I see. I just installed AHK_MicMute and it's working fine for me.. I'm not playing any MP games tho.
I don't use push-to-talk, I just need an on/off switch for my mic.

**Comment by Uronic** [comment]
> > I have stopped using AHK MicMute for a while since I am playing games which possibly falsely ban you for using Autohotkey (The backend of MicMute).
> > I do not remember having this issue when I did use it though.
> > I use Voicemeeter's MacroButtons in administrator mode for push to talk now if you're wondering.
> 
> I see. I just installed AHK_MicMute and it's working fine for me.. I'm not playing any MP games tho. I don't use push-to-talk, I just need an on/off switch for my mic.

You can do the same thing on MacroButtons.

**Comment by roughnecks** [comment]
> > > I have stopped using AHK MicMute for a while since I am playing games which possibly falsely ban you for using Autohotkey (The backend of MicMute).
> > > I do not remember having this issue when I did use it though.
> > > I use Voicemeeter's MacroButtons in administrator mode for push to talk now if you're wondering.
> > 
> > 
> > I see. I just installed AHK_MicMute and it's working fine for me.. I'm not playing any MP games tho. I don't use push-to-talk, I just need an on/off switch for my mic.
> 
> You can do the same thing on MacroButtons.

Yeah, also just noticed they added Mouse Buttons to the keyboard buttons list - gonna give it a try, thanks!

**Comment by roughnecks** [comment]
> > You can do the same thing on MacroButtons.
> 
> Yeah, also just noticed they added Mouse Buttons to the keyboard buttons list - gonna give it a try, thanks!

Although I won't have any visual confirmation on (un)muted mic, how do you cope with that?

**Comment by Uronic** [comment]
> > > You can do the same thing on MacroButtons.
> > 
> > 
> > Yeah, also just noticed they added Mouse Buttons to the keyboard buttons list - gonna give it a try, thanks!
> 
> Although I won't have any visual confirmation on (un)muted mic, how do you cope with that?

I have sound feedback with Voicemeeter's recorder. Whenever you load a file to the recorder it plays it so it gives me a nice push to talk on/off sound. Try searching voicemeeter soundboard on google.

**Comment by roughnecks** [comment]
> > > > You can do the same thing on MacroButtons.
> > > 
> > > 
> > > Yeah, also just noticed they added Mouse Buttons to the keyboard buttons list - gonna give it a try, thanks!
> > 
> > 
> > Although I won't have any visual confirmation on (un)muted mic, how do you cope with that?
> 
> I have sound feedback with Voicemeeter's recorder. Whenever you load a file to the recorder it plays it so it gives me a nice push to talk on/off sound. Try searching voicemeeter soundboard on google.

Oh OK, I know already how to use the recorder but the icon overlay (and/or in tray) is still a nicer option for me.
