### ISSUE TITLE
default profile also mute my speakers

### ISSUE THREAD

**Issue by toxic0berliner** [SaifAqqad/AHK_MicMute#55]
Hello,

Somehow when using my Jabra phs200, the default profile mutes not only it's microphone but also the speaker.
I've tested with the default profile set to mute "default", or the "jabra mic..." or "all microphones" and it still heppens.
The strange thing is that if I create a "Profile 2" with the same settings it works fine and only the mic gets muted and not the speaker.
Looking at the settings.json, both default and profile2 entries are exactly identical except profile name...

No idea what is special about the Default profile that fails. That did not happen with another PC and another soundard... But works fine with my other all-in-one usb jabra headser for example.

Not sure how to give some more logs or details, I'm not sure how I can help further...

**Comment by SaifAqqad** [comment]
Could you give me a copy of the log when the default profile is set?

you can open the log by clicking the `Help` option in the tray menu while holding <kbd>Shift</kbd> and then click `Copy Log`
![image](https://user-images.githubusercontent.com/47293197/156883223-387c84f4-ba5c-48bf-ad30-159ed54de482.png)

**Comment by toxic0berliner** [comment]
This is the log and `config.json` : 
```#1 51750: MicMute v1.2.4
#2 51750: [Main] Running as user ***, A_IsAdmin = 0
#3 51750: [UI] Creating 'config' window
#4 52062: [UI] Creating 'about' window
#5 52296: [Main] Initilizing MicMute
#6 52296: [Config] Importing config.json
#7 52453: [Tray] Initilizing tray menu
#8 52484: [Main] Switching to profile 'Default'
#9 52484: [OSD] Creating OSD window
#10 52546: [MicrophoneController] Enabled: [ Interphone avec annulation d'écho (Jabra SPEAK 510 USB) ]
#11 52578: [Config] exporting the config object
#12 52578: [Main] MicMute startup took 844ms
#13 62640: [Updater] Fetching tag_name from https://api.github.com/repos/SaifAqqad/AHK_MicMute/releases/latest
#14 95671: [MicrophoneController] Disabled: [ Interphone avec annulation d'écho (Jabra SPEAK 510 USB) ]
#15 95671: [Main] Switching to profile 'Profile 2'
#16 95671: [OSD] Creating OSD window
#17 95671: [MicrophoneController] Enabled: capture
#18 108968: [MicrophoneController] Disabled: capture
#19 108968: [Main] Switching to profile 'Default'
#20 108968: [OSD] Creating OSD window
#21 108968: [MicrophoneController] Enabled: [ Interphone avec annulation d'écho (Jabra SPEAK 510 USB) ]
```

```{
	"AllowUpdateChecker": 1,
	"DefaultProfile": "Default",
	"ForceMicrophoneState": 0,
	"MuteOnStartup": 0,
	"PreferTheme": -1,
	"Profiles": [
		{
			"afkTimeout": 0,
			"ExcludeFullscreen": 0,
			"LinkedApp": "",
			"Microphone": [
				{
					"MuteHotkey": "AppsKey",
					"Name": "All Microphones",
					"PushToTalk": 0,
					"UnmuteHotkey": "AppsKey"
				}
			],
			"OnscreenFeedback": 1,
			"OnscreenOverlay": 0,
			"OSDPos": {
				"x": 1922,
				"y": 1100
			},
			"OverlayPos": {
				"x": -1,
				"y": -1
			},
			"OverlayShow": "2",
			"OverlayUseCustomIcons": 0,
			"ProfileName": "Default",
			"PTTDelay": 100,
			"SoundFeedback": 0,
			"SoundFeedbackDevice": "Default",
			"SoundFeedbackUseCustomSounds": 0,
			"UpdateWithSystem": 1
		},
		{
			"afkTimeout": 0,
			"ExcludeFullscreen": 0,
			"LinkedApp": "",
			"Microphone": [
				{
					"MuteHotkey": "AppsKey",
					"Name": "Default",
					"PushToTalk": 0,
					"UnmuteHotkey": "AppsKey"
				}
			],
			"OnscreenFeedback": 1,
			"OnscreenOverlay": 0,
			"OSDPos": {
				"x": 1926,
				"y": 1098
			},
			"OverlayPos": {
				"x": -1,
				"y": -1
			},
			"OverlayShow": "2",
			"OverlayUseCustomIcons": 0,
			"ProfileName": "Profile 2",
			"PTTDelay": 100,
			"SoundFeedback": 0,
			"SoundFeedbackDevice": "Default",
			"SoundFeedbackUseCustomSounds": 0,
			"UpdateWithSystem": 1
		}
	],
	"SwitchProfileOSD": 1
}```

I didn't realize I could change the default profile in there so it just fixed my issue by changing the default profile to `Profile 2`. 
Well, not fixed the issue, I still see the speaker being muted even in the little icon left of the clock when I press my toggle and I'm using the Default profile, but now MicMute starts with my own profile on start that doesn't have the issue ;) So urgency for this drops way way down ;)

**Comment by SaifAqqad** [comment]
I think the problem is that the device's driver is using the same exact name for both the microphone and the speaker, usually, devices like this differentiate between the recording and the playback devices by assigning them different names (like the corsair device in the pics below)

![image](https://user-images.githubusercontent.com/47293197/156888558-39ef5f57-4713-40ef-bae3-552454af6f7c.png)
![image](https://user-images.githubusercontent.com/47293197/156888561-d725ed14-c98a-455f-b2e8-e8f7c1849069.png)

does the problem persist If you change the microphone's name?

**Comment by toxic0berliner** [comment]
You nailed it, I renamed both : 
![image](https://user-images.githubusercontent.com/10488124/156928585-d5229a29-3c05-4101-85ab-428d49eb32e8.png)
![image](https://user-images.githubusercontent.com/10488124/156928596-52255fbc-c10e-4ec5-8520-ff74d5e363bb.png)
And the problem went away even in the default profile !
Wasn't sure I was allowed to rename it since it's a corporate PC and I'm not admin on it... But I did and it fixed it !  I'll test later if that resists reboots and if other models of the same speaker kindly use my new name of if I have to rename them for this to work.
Nevertheless I'm already fully avoiding the issue now that my default profile is Profile2 ;)

Unless you see something that could help you mute only input sources and not outputs and it makes sense for you to change it, we can safely close this even as wontfix and there are at least 2 workarounds for other users in this thread ;)

Also, let me take the opportunity to highlight one of the things I love about this tool : I can use it as a simple user without admin rights on my corporate machine, so avoiding priviledge escalation requirements in install/update/autostart/run is really a great feature for me ;) Thanks a lot for your time and effort !

**Comment by SaifAqqad** [comment]
That's great, I'm still gonna fix this issue though. It should not touch output devices at all.
