### ISSUE TITLE
Autostart: how does it work?

### ISSUE THREAD

**Issue by roughnecks** [SaifAqqad/AHK_MicMute#62]
I cannot find MicMute in any place for it to autostart - registry, shell:startup, scheduled tasks..
I also unticked the option for start at boot but every time I exit the app and run it again, the flag is set again.

Can you help?

**Comment by SaifAqqad** [comment]
It create a scheduled task called `MicMute`
![image](https://user-images.githubusercontent.com/47293197/165602394-7518c253-4cae-439b-9086-3f8690bd047f.png)

**Comment by roughnecks** [comment]
Oh, I get it now. I had a task called MicMute already set-up from another app with the same name, so I believe it failed creating the task.
