### ISSUE TITLE
Addition to voicemeeter integration

### ISSUE THREAD

**Issue by Uronic** [SaifAqqad/AHK_MicMute#67]
Per strip selection.

In Voicemeeter's MacroButtons you can modify options per strip.

For example:

strip[0].B1 = 0;

This will disable B1 in strip 0.

![image](https://user-images.githubusercontent.com/42480079/176543437-161829fe-d613-4025-ae8c-0a038d1ba054.png)

**Comment by SaifAqqad** [comment]
So instead of using `strip[1].mute` it would just use `strip[1].B1` or whatever property the user chooses, and it would keep track of the state of that property as if it was the "mute" state

**Comment by SaifAqqad** [comment]
@Uronic Can you explain what do you mean by 'Per strip selection'

**Comment by Uronic** [comment]
> @Uronic Can you explain what do you mean by 'Per strip selection'?

Let's say you have more than 1 input device in voicemeeter. Per strip selection would mean that you can set one of those strips as the PTT device and choose whether B1 or B2 or B3 or all is toggled/push to talk

**Comment by SaifAqqad** [comment]
Sorry this took so long, I implemented it as an optional config for each microphone called `VMRStripProperty`, which can be set to any property you want micmute to treat as the "mute" state. 

Note that it can only be applied to strips, and it can only be set in the config.json file and not in the UI.

You can hold <kbd>Shift</kbd> when clicking `Edit configuration` to open the config.json in an editor.
