### ISSUE TITLE
[Feature Request] Intelligent hotkey: long press PTT, short press toggle

### ISSUE THREAD

**Issue by deejayy** [SaifAqqad/AHK_MicMute#69]
I'm not sure what else to add to the title, let me know if it needs clarification.

And of course thank you for considering!

**Comment by SaifAqqad** [comment]
That's a great idea, I will definitely look into it

**Comment by SaifAqqad** [comment]
I've implemented this as 'Hybrid PTT' which is an option for PTT hotkeys
![image](https://user-images.githubusercontent.com/47293197/183293790-522bef95-5fc8-45c0-bcb7-c0f3619ceecf.png)

You can try it out in the [dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit)  right now, if you have any questions or feedback, leave a comment below.

**Comment by deejayy** [comment]
Kudos and thank you! I'll try it out! 🙏🏻

**Comment by deejayy** [comment]
All right, checked, this is just pure awesomeness! I can't thank you enough.

Though this approach is best when the mic is off.

If the mic is on, I'm thinking that PTT functionality does not make too much sense. What's your opinion?
My concern is the there will be a slight (few milliseconds) mute when holding the button and it will turn the mic off at the end.

**Comment by SaifAqqad** [comment]
>If the mic is on, I'm thinking that PTT functionality does not make too much sense. What's your opinion?

Right now, when the mic is on, it just works as a toggle. I think it makes sense, because in that case you would have used the hotkey as a toggle to be able to turn the mic on

**Comment by deejayy** [comment]
You must be right, it's my way of thinking what might be misleading me. Thanks again for the effort!
