### ISSUE TITLE
Virustotal.com flags the executable as malicious

### ISSUE THREAD

**Issue by github-roland** [SaifAqqad/AHK_MicMute#72]
some security vendors on Virustotal.com flag the micmute.exe executable as malicious. Is this a problem? dont know how many flaggers it takes before it gets serious ?

![Capture](https://user-images.githubusercontent.com/117074922/198976852-9b65a125-ca8d-4524-95ac-2a358aa88076.JPG)

**Comment by SaifAqqad** [comment]
it's a false detection, all of these AVs flag anything related to Autohotkey as malicious.

I submit new releases to microsoft so they remove false detection from windows defender, that should be enough for most people so they can install MicMute without defender deleting it.
