### ISSUE TITLE
[Feature] Add microphone actions

### ISSUE THREAD

**Issue by SaifAqqad** [SaifAqqad/AHK_MicMute#75]
for example, running a command/program when muting/unmuting a specific microphone.

Might consider abstracting the existing feedback options (sound/on-screen feedback) as additional microphone actions.

**Comment by github-roland** [comment]
Hi thanks for this one, i would really love it when i can connect an action to muting/unmuting all mic's. like turning a light on and off. In my case i would like to start a batch file with a parameter.

**Comment by SaifAqqad** [comment]
@github-roland it's finally out in [v1.2.7](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/1.2.7) 😅

**Comment by github-roland** [comment]
Works great! very happy with the new function. Thanks!!!!
