### ISSUE TITLE
Onscreen overlay shows when program runs, set to "On-mute only"

### ISSUE THREAD

**Issue by SquiIIiam** [SaifAqqad/AHK_MicMute#77]
When the program is started, the onscreen overlay icon shows the mic unmuted. Toggling the mute on and off produces the desired behavior of not showing the unmuted icon. Show Overlay is set to On-mute only.

**Comment by SaifAqqad** [comment]
Should be fixed in [1.2.6](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/1.2.6) :D
