### ISSUE TITLE
[Feature] Always display OSD

### ISSUE THREAD

**Issue by harsh0596** [SaifAqqad/AHK_MicMute#79]
I would like to be able to see the OSD at all times to check if my mic is muted or not. I understand I could use the system tray icon but I can't see that when im in a fullscreen game. I like to keep the OSD on my 2nd monitor

**Comment by SaifAqqad** [comment]
This is already an option, just enable it in the config.

[Onscreen Overlay](https://github.com/SaifAqqad/AHK_MicMute#3-on-screen-overlay)

**Comment by harsh0596** [comment]
CTRL + ALT + F9 does nothing for me - im on windows 11 btw

**Comment by SaifAqqad** [comment]
@harsh0596 did you turn on the option in the configuration?
It's the last option under `Feedback`
![image](https://user-images.githubusercontent.com/47293197/204966238-e52d0a87-ba80-4708-90c6-435416d9bc13.png)

**Comment by harsh0596** [comment]
i dont have this option

![image](https://user-images.githubusercontent.com/11883323/204997869-b5e4f11c-548e-488b-84b8-5460d2e02aef.png)

**Comment by harsh0596** [comment]
ok so the option appeared after i created another profile apart from default
i am having an issue where the overlay randomly disappears while im not even in game
