### ISSUE TITLE
[bug] losing mouse input whenever mic is unmuted 

### ISSUE THREAD

**Issue by roughnecks** [SaifAqqad/AHK_MicMute#82]
These are my settings:

https://i.imgur.com/u3KhObg.jpeg
https://i.imgur.com/BZ8AMxU.jpeg
https://i.imgur.com/v8XOTd0.jpeg
https://i.imgur.com/2bmEW4g.jpeg

When I want to unmute my mic, I press the side mouse button and it unmutes but I lose all inputs from my mouse; I can't click on anything anymore. Workaround for the moment is to block my Windows session (WIN + L) and get back.

If I can help providing logs or whatever you need, please let me know.
Thanks

**Comment by successtheman** [comment]
I believe I am experiencing this as well

**Comment by SaifAqqad** [comment]
@successtheman could you share your `config.json` file

**Comment by successtheman** [comment]
@SaifAqqad it won't let me upload just the json file so I put it in a zip, here it is
[config.json.zip](https://github.com/SaifAqqad/AHK_MicMute/files/10996374/config.json.zip)

**Comment by SaifAqqad** [comment]
@successtheman it's definitely not related to the 1.2.7 update, @roughnecks had it happen on 1.2.6 as well.

I tried replicating both configs and unfortunately I couldn't reproduce it :(

**Comment by successtheman** [comment]
> @successtheman it's definitely not related to the 1.2.7 update, @roughnecks had it happen on 1.2.6 as well.
> 
> I tried replicating both configs and unfortunately I couldn't reproduce it :(

@SaifAqqad I tested it and it only is an issue on 1.2.7 so I don't know what else could be causing it. I reverted back to 1.2.6 and have had no troubles since

**Comment by roughnecks** [comment]
Since I got 1.2.7, it never happened anymore to me, so.. ¯\_(ツ)_/¯

**Comment by SaifAqqad** [comment]
> the program doesn't detect the mute and unmute

@successtheman do you mean the overlay/sound feedback? or do you mean subsequent hotkey clicks?

**Comment by successtheman** [comment]
> > the program doesn't detect the mute and unmute
> 
> @successtheman do you mean the overlay/sound feedback? or do you mean subsequent hotkey clicks?

I believe both, the mic will not mute/unmute unless I spam click the icon or spam my hotkey in these situations. I know because I was in discord testing if it detected any input

**Comment by successtheman** [comment]
> > the program doesn't detect the mute and unmute
> 
> @successtheman do you mean the overlay/sound feedback? or do you mean subsequent hotkey clicks?

@SaifAqqad believe both, the mic will not mute/unmute unless I spam click the tray icon or spam my hotkey in these situations. I know because I was in discord testing if it detected any input

**Comment by successtheman** [comment]
Any word on this? I migrated away from a scoop managed installation to a static standalone one on 1.2.6 as that version worked as intended for me. As long as it keeps working I'll probably stay on that version I guess

**Comment by SaifAqqad** [comment]
Sadly, I can't reproduce this at all, literally not even once :(

**Comment by SaifAqqad** [comment]
@successtheman I finally had this happen to me while in-game, I think i found the reason it's happening but I'm not 100% sure.
Could you please test the latest [dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit) and check?

Btw for reference, it's commit 523f7d383334745ad945df08d85a6d34cb69ae73 that might fix it.

**Comment by successtheman** [comment]
> @successtheman I finally had this happen to me while in-game, I think i found the reason it's happening but I'm not 100% sure. Could you please test the latest [dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit) and check?
> 
> Btw for reference, it's commit [523f7d3](https://github.com/SaifAqqad/AHK_MicMute/commit/523f7d383334745ad945df08d85a6d34cb69ae73) that might fix it.

The dev build seems to fix it I will keep testing it today so see if I notice anything happening again
