### ISSUE TITLE
[Feature] Microphone volume lock

### ISSUE THREAD

**Issue by kclonline** [SaifAqqad/AHK_MicMute#86]
Hi, I wonder if the program can add the function of locking the microphone volume size? Looking forward to it.

**Comment by SaifAqqad** [comment]
I'm not sure I understand what you mean, could you elaborate?

**Comment by kclonline** [comment]
I’m not sure if it’s possible to add a feature to lock the volume of the microphone so that it is not changed by any program. Even if it is changed, it will immediately be changed back to the set microphone volume. This is because when some programs are running, they will automatically adjust the volume of the microphone. And if you are recording at the time, sudden changes in volume will make the recorded sound noticeably louder and softer.

**Comment by roughnecks** [comment]
I use soundvolumeview with a simple batch script I wrote which runs at startup and loops every N seconds to set desired volume %.
I could share it if you want, but if it could be achieved by MicMUTE it'd be even better.

**Comment by kclonline** [comment]
> I use soundvolumeview with a simple batch script I wrote which runs at startup and loops every N seconds to set desired volume %. I could share it if you want, but if it could be achieved by MicMUTE it'd be even better.

Thank you, can you share it with me to try? 
Before this, I also looked for some programs, but still felt the sound getting louder and softer when receiving the radio. So I thought if MicMute could be built-in and make the sound no longer fluctuate, it would be really great.

**Comment by roughnecks** [comment]
[Desktop.zip](https://github.com/SaifAqqad/AHK_MicMute/files/11519802/Desktop.zip)

They are 2 files, the vbs must be autostarted with windows and the bat can be saved under your documents, or where you prefer.
You have to change paths inside both scripts and also remove the comments (I wrote them to explain the various settings).

**Comment by roughnecks** [comment]
https://www.nirsoft.net/utils/sound_volume_view.html

**Comment by SaifAqqad** [comment]
Sounds useful, will look into this

**Comment by SaifAqqad** [comment]
I just a pushed a commit that implements this feature, you can test it right now in the [dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit).

**Comment by roughnecks** [comment]
Thanks
