### ISSUE TITLE
"UseCustomIcons" not work anymore

### ISSUE THREAD

**Issue by rdayltx** [SaifAqqad/AHK_MicMute#90]
Hi,
UseCustomIcons feature not work in the latest version (1.2.9).

![image](https://github.com/SaifAqqad/AHK_MicMute/assets/82792422/fddd12f8-feb5-4354-a062-10a1d2d41cbe)

**Comment by SaifAqqad** [comment]
Thanks for reporting the issue.

This should be fixed in commit c78c51da7e3a0567d665ec0d4fa59d462a5a6e7b, you can test it in the [latest dev build](https://github.com/SaifAqqad/AHK_MicMute/releases/tag/latest_commit).
