### ISSUE TITLE
slide out whenever running other programs requiring admin

### ISSUE THREAD

**Issue by 23floors** [SaifAqqad/AHK_MicMute#95]
hello saif.

before anything else, i want to say THANK YOU! for having crafted, shared, and even supported this software package.

AHK_MicMute is functional, flexible, and reliable.  i use it every day and it instantly improved my phone / computer experience

you're on my list for that ko-fi thing

now, i noticed one detail, not necessarily a bug, however quite possibly also not intentional or immediately obvious

i run windows with a normal user account.  whenever i need to run something requiring admin, i provide the credentials then and there

every time i do run any other program requiring admin, a few moments later, AHK_MicMute shows that slide-out message on the lower right part of my screen  - the same one that shows when the program starts up

again, not necessarily a bug, however i thought it worth finally taking a few moments to mention

ZERO rush / urgency on this

again, many thanks and best regards!

**Comment by SaifAqqad** [comment]
Thank you so much for the kind words :D

About the notification, I added it purposefully to avoid confusing people when MicMute doesn't work while they're in a full screen game, however you can easily disable it by right clicking the notification and choosing _Turn off all notifications for MicMute_

![image](https://github.com/SaifAqqad/AHK_MicMute/assets/47293197/b985bba0-626a-47a3-a643-532a116a8328)

**Comment by Pitchblack3** [comment]
When using the start on boot it doesnt start as admin so it prompts this notification quite often. Disabling the notification doesnt solve the problem that you cant mute when a program starts as admin. Is there a way arround this or do i have to start the program as admin using a script on boot?

**Comment by SaifAqqad** [comment]
@Pitchblack3 Turning on the start on boot option while running MicMute as admin will also make the startup task run as admin

**Comment by Pitchblack3** [comment]
Hadnt tried that combination yet but it works! Thanks so much, love the program great work!
