### ISSUE TITLE
No UI

### ISSUE THREAD

**Issue by Tatsu2316** [SaifAqqad/AHK_MicMute#96]
when i try to open the ui anywhere other then downloads folder it says this

![image](https://github.com/SaifAqqad/AHK_MicMute/assets/120792104/96336209-d1cf-4eb4-bc36-79d0d9436d92)

**Comment by Tatsu2316** [comment]
it was beacause of non-english characters in the directory name

**Comment by SaifAqqad** [comment]
> it was beacause of non-english characters in the directory name

I re-opened this issue since this is an actual bug in the UI library that I'm using, as having non-English characters in the directory shouldn't cause it to fail.
