### ISSUE TITLE
move onscreen overlay

### ISSUE THREAD

**Issue by immortal-kid** [SaifAqqad/AHK_MicMute#99]
allow move on-screen overlay to different position.

**Comment by SaifAqqad** [comment]
Press <kbd>Ctrl</kbd> <kbd>Alt</kbd> <kbd>F10</kbd> and the overlay will be unlocked so you can move it wherever you want, afterwards press the same combination to lock it.

**Comment by immortal-kid** [comment]
it would have been nice if we are able to resize and change the opacity :)

**Comment by SaifAqqad** [comment]
You can already set the overlay size in the config 
![image](https://github.com/SaifAqqad/AHK_MicMute/assets/47293197/a64dcd48-3e68-4688-b45e-df3b35d65784)

As for the opacity, please open a new issue and I'll look into it when I have the time.

**Comment by carlox97** [comment]
The overlay disappears in fullscreen games, is there a way around this?

**Comment by SaifAqqad** [comment]
> The overlay disappears in fullscreen games, is there a way around this?

You need to set your game to "Windowed Fullscreen" or "Borderless Fullscreen"

**Comment by vertopolkaLF** [comment]
> Press Ctrl Alt F10 
Would be nice to have that info in the program itself.
